### PR TITLE
Set explicit culture for culture dependent tests

### PR DESCRIPTION
**Pull request by victormarante**

### CODE REVIEW

**Comment by victormarante** [comment]
I didn't find any way to set  invariant culture, but I think this will suffice.

**Comment by victormarante** [comment]
I didn't find any way to set  invariant culture, but I think this will suffice.

**Comment by ModernRonin** [comment]
thank you! 

I will be able to look at this and the other PR only on the weekend, got a bit of stress in my work.

**Review by ModernRonin — APPROVED** [review]

**Comment by ModernRonin** [comment]
actually, this one was very quick => done

**Pull request merged**
